server:
  port: 10000

#服务发现客户端
eureka:
  instance:
    #向Eureka注册时，是否使用IP地址+端口号作为服务实例的唯一标识。推荐设置为true
    prefer-ip-address: true

    #============分界线================
    #以下为基本不需要配置的属性，属性的值为默认值

    #服务续约的调用时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效的时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    #非安全的通信端口号
    non-secure-port: 80
    #安全的通信端口号
    secure-port: 443
    #是否启用非安全的通信端口号
    non-secure-port-enabled: true
    #是否启用安全的通信端口号
    secure-port-enabled: false

  client:
    #是否将自身的实例信息注册到Eureka服务端
    register-with-eureka: true
    #是否拉取并缓存其他服务注册表副本到本地
    fetch-registry: true
    #注册到哪个Eureka服务实例
    service-url:
      defaultZone: http://localhost:8761/eureka/

    #============分界线================
    #以下为基本不需要配置的属性，属性的值为默认值

    #更新其他服务注册表时间间隔，默认30秒
    registry-fetch-interval-seconds: 30
    #更新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    #初始化实例信息到Eureka服务端的间隔时间，单位为秒
    initial-instance-info-replication-interval-seconds: 40
    #轮询Eureka服务端地址更改的间隔时间，单位为秒。
    #当我们与Sping Cloud Config配合，动态刷新Eureka的service url地址时需要关注该参数
    eureka-service-url-poll-interval-seconds: 300
    #读取Eureka Server信息的超时时间，单位为秒
    eureka-server-read-timeout-seconds: 8
    #连接Eureka Server的超时时间，单位为秒
    eureka-server-connect-timeout-seconds: 5
    #从Eureka客户端到所有Eureka服务端的连接总数
    eureka-server-total-connections: 200
    #从Eureka客户端到每个Eureka服务端主机的连接总数
    eureka-server-total-connections-per-host: 50
    #Eureka服务连接的空闲关闭时间，单位为秒
    eureka-connection-idle-timeout-seconds: 30
    #心跳连接池的初始化线程数
    heartbeat-executor-thread-pool-size: 2
    #心跳超时重试延迟时间的最大乘数值
    heartbeat-executor-exponential-back-off-bound: 10
    #缓存刷新线程池的初始化线程数
    cache-refresh-executor-thread-pool-size: 2
    #缓存刷新重试延迟时间的最大乘数值
    cache-refresh-executor-exponential-back-off-bound: 10
    #使用DNS来获取Eureka服务端的service url
    use-dns-for-fetching-service-urls: false
    #是否优先使用处于相同Zone的Eureka服务端
    perfer-same-zone-eureka: true
    #获取实例时是否过滤，仅保留UP状态的实例
    filter-only-up-instances: true

#数据源的配置
spring:
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none